### ISSUE TITLE
If OCTGN disconnects in the middle of a running script, no more scripts can be run

### ISSUE THREAD

**Issue by db0** [kellyelton/OCTGN#1347]
OCTGN needs to terminate all currently running python scripts upon reconnection. Currently if one client disconnects while a script was running, it prevents any more scripts being run from the player currently who was running it, leading to a broken game. I suspect current python processes remain open on the client somehow. I got a log it if will help but it's a very common and easily replicatable phenomenon.

**Comment by brine** [comment]
I was searching through the issue tracker looking for related tickets to link this to, but apparently this bug has never actually made it to the issue tracker before...  funny since it's so frequently discussed at other locations.

Anyway, I'm not 100% sure how the reconnect mechanics interact with python, but yeah maybe it wouldn't hurt to have it completely nuke the python environment and reload it?

**Comment by brine** [comment]
I've personally tried to replicate it several times on my end and I could never get the reconnect to trigger at the point where a script thread is still running, if you have a piece of code that can easily replicate the bug than it would be useful here

**Comment by db0** [comment]
Have you tried using a dialogue to pause the script, to give you a chance
to disconnect? Otherwise it's tricky to get because in single player
scripts are almost instant. You could try in actual multilayer with obs
running to slow things down perhaps.

**Comment by kellyelton** [comment]
That dialog idea is pretty good, I'll have to give that a shot.

**Comment by kellyelton** [comment]
I think the problem here might be that if you do a call that's networked while you're disconnected, it'll cause a socket exception, which then bubbles up and blows up the script engine.

I would also like to try and add a layer that recovers the script engine incase the whole thing blows up, but that will mean(Like I was just telling brine yesturday) that it'll nuke ALL global variables(not the networked ones, but the python ones).

**Comment by kellyelton** [comment]
Ok, so after a bit of research it looks like the problem is the `rnd` call firing when you're disconnected. They have the dialog open, click 'OK' while disconnected, which continues on and fires a `rnd` in your code, which then freezes the script engine forever.

**Comment by db0** [comment]
I don't think it's just the rnd() (although I hope it's such an easy fix) because I've seen this happen very consistently, and I doubt it managed to hit the rnd() call every single time.

**Comment by kellyelton** [comment]
Yeah it basically was just that. that's the only thing in octgn that would stop the python engine from executing.

**Comment by db0** [comment]
Well, here's wishing. I'll let you know if it happens again after this change is live.
