### ISSUE TITLE
Flip Cards!

### ISSUE THREAD

**Issue by Beornd63** [kellyelton/OCTGN#842]
Since an update this week, the card flipping action doesn´t work for me.
If i use the action, the card  doesn´t change the side. But only for me not for my opponnent. i see that the action  was done in  the chat file. 
I deleted complete octgn and reinstalled it. But nothing happens. I told them in AGoT chat  one of the programmer but he told that he heart first time about this Problem.

**Comment by brine** [comment]
So you know how restarting your computer fixes the issue? Well, it turns out your computer keeps a TickCount for as long as it stays running.  After about 29 days, it hits its maximum value, then becomes a very large negative number, and continues ticking up.  So basically, if you leave you computer running without shutting it off, its tickCount becomes negative and screws up OCTGN in a bunch of places (OCTGN uses TickCount as a sort of timer).

**Comment by db0** [comment]
This is fixed?! Wohoo!

**Comment by brine** [comment]
Only people who leave their computers running for over 28-ish days would experience the bug. So if you think about it, our previous fix of restarting their computer was actually doing them a favour.

**Comment by Gravecorp** [comment]
my average run time on my comp is about 1-2 months at a time :P
